#!/usr/bin/env python3
"""
Initialize Docusaurus Documentation Site

Usage: python init_docusaurus.py <site-name> --title "My Docs"
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime


def create_docusaurus_config(site_name: str, title: str) -> str:
    """Create docusaurus.config.js."""
    return f'''// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require('prism-react-renderer').themes.github;
const darkCodeTheme = require('prism-react-renderer').themes.dracula;

/** @type {import('@docusaurus/types').Config} */
const config = {{
  title: '{title}',
  tagline: 'Documentation Site',
  favicon: 'img/favicon.ico',

  // Set the production url of your site here
  url: 'https://{site_name}.example.com',
  // Set the /<baseUrl>/ pathname under which your site is served
  baseUrl: '/',

  // GitHub pages deployment config
  organizationName: 'your-org',
  projectName: '{site_name}',

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang
  i18n: {{
    defaultLocale: 'en',
    locales: ['en'],
  }},

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({{
        docs: {{
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/your-org/{site_name}/tree/main/',
        }},
        blog: {{
          showReadingTime: true,
          editUrl:
            'https://github.com/your-org/{site_name}/tree/main/',
        }},
        theme: {{
          customCss: require.resolve('./src/css/custom.css'),
        }},
      }}),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({{
      // Replace with your project's social card
      image: 'img/social-card.jpg',
      navbar: {{
        title: '{title}',
        logo: {{
          alt: 'Logo',
          src: 'img/logo.svg',
        }},
        items: [
          {{
            type: 'docSidebar',
            sidebarId: 'tutorialSidebar',
            position: 'left',
            label: 'Tutorial',
          }},
          {{to: '/blog', label: 'Blog', position: 'left'}},
          {{
            href: 'https://github.com/your-org/{site_name}',
            label: 'GitHub',
            position: 'right',
          }},
        ],
      }},
      footer: {{
        style: 'dark',
        links: [
          {{
            title: 'Docs',
            items: [
              {{
                label: 'Tutorial',
                to: '/docs/intro',
              }},
            ],
          }},
          {{
            title: 'Community',
            items: [
              {{
                label: 'Stack Overflow',
                href: 'https://stackoverflow.com/questions/tagged/docusaurus',
              }},
              {{
                label: 'Discord',
                href: 'https://discordapp.com/invite/docusaurus',
              }},
            ],
          }},
          {{
            title: 'More',
            items: [
              {{
                label: 'Blog',
                to: '/blog',
              }},
              {{
                label: 'GitHub',
                href: 'https://github.com/your-org/{site_name}',
              }},
            ],
          }},
        ]}},
      prism: {{
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
        additionalLanguages: ['python', 'javascript', 'bash', 'json'],
      }},
    }}),
}};

module.exports = config;
'''


def create_sidebars() -> str:
    """Create sidebars.js."""
    return '''// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
'''


def create_intro_doc(site_name: str) -> str:
    """Create intro documentation."""
    return f'''---
sidebar_position: 1
---

# Welcome to {site_name.title()}

This is the documentation site for **{site_name}**.

## Quick Start

### Step 1: Installation

```bash
npm install
```

### Step 2: Run Locally

```bash
npm start
```

### Step 3: Build for Production

```bash
npm run build
```

## Documentation Structure

- **docs/** - Main documentation files
- **blog/** - Blog posts
- **src/** - Custom React components
- **static/** - Static assets

## Contributing

1. Fork the repository
2. Create a branch: `git checkout -b feature/new-doc`
3. Make your changes
4. Run `npm run build` to verify
5. Submit a pull request

## Need Help?

- Check existing [GitHub Issues](https://github.com/your-org/{site_name}/issues)
- Ask in [Discussions](https://github.com/your-org/{site_name}/discussions)
- Contact the maintainers
'''


def create_blog_post() -> str:
    """Create sample blog post."""
    today = datetime.now().strftime('%Y-%m-%d')
    return f'''---
slug: welcome-to-our-new-docs
title: Welcome to Our New Documentation
authors: [team]
tags: [announcement, docs]
---

We're excited to announce our new documentation site!

## What's New

- **Improved Navigation**: Find what you need faster
- **Code Examples**: More practical examples
- **Search**: Find content instantly
- **Dark Mode**: Easier on the eyes

## Getting Started

Check out our [Introduction](/docs/intro) to get started.

## Feedback

We'd love to hear your feedback! Open an issue on GitHub or reach out to the team.
'''


def create_custom_css() -> str:
    """Create custom CSS."""
    return '''/* Custom CSS for Docusaurus */

:root {{
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
}}

/* For readability concerns, you should choose a lighter palette in dark mode. */
[data-theme='dark'] {{
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-darker: #1fa588;
  --ifm-color-primary-darkest: #1a8870;
  --ifm-color-primary-light: #29d5b0;
  --ifm-color-primary-lighter: #32d8b4;
  --ifm-color-primary-lightest: #4fddbf;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
}}

/* Custom hero section */
.hero {{
  padding: 4rem 0;
  text-align: center;
}}

/* Custom code blocks */
.code-block {{
  border-radius: 8px;
}}

/* Custom navigation */
.navbar {{
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}}
'''


def create_dockerfile() -> str:
    """Create Dockerfile for Docusaurus."""
    return '''# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built files
COPY --from=builder /app/build /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
    CMD wget -qO- http://localhost/health || exit 1

CMD ["nginx", "-g", "daemon off;"]
'''


def create_nginx_conf() -> str:
    """Create nginx configuration."""
    return '''server {{
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {{
        expires 1y;
        add_header Cache-Control "public, immutable";
    }}

    # SPA routing
    location / {{
        try_files $uri $uri/ /index.html;
    }}

    # Health check endpoint
    location /health {{
        access_log off;
        return 200 "healthy\\n";
        add_header Content-Type text/plain;
    }}
}}
'''


def create_k8s_deployment(site_name: str) -> str:
    """Create Kubernetes deployment."""
    return f'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {site_name}
  labels:
    app: {site_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {site_name}
  template:
    metadata:
      labels:
        app: {site_name}
    spec:
      containers:
      - name: {site_name}
        image: {site_name}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {site_name}
  labels:
    app: {site_name}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {site_name}
'''


def create_package_json(site_name: str) -> str:
    """Create package.json."""
    return f'''{{
  "name": "{site_name}",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  }},
  "dependencies": {{
    "@docusaurus/core": "3.1.0",
    "@docusaurus/preset-classic": "3.1.0",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }},
  "devDependencies": {{
    "@docusaurus/module-type-aliases": "3.1.0",
    "@docusaurus/types": "3.1.0"
  }},
  "browserslist": {{
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 3 chrome version",
      "last 3 firefox version",
      "last 5 safari version"
    ]
  }},
  "engines": {{
    "node": ">=18.0"
  }}
}}
'''


def create_readme(site_name: str, title: str) -> str:
    """Create README."""
    return f'''# {title}

Documentation site built with Docusaurus.

## Quick Start

### Local Development

```bash
npm install
npm start
```

This starts a local development server and opens a browser window.

### Build

```bash
npm run build
```

### Deploy

```bash
# Build Docker image
docker build -t {site_name}:latest .

# Deploy to Kubernetes
python scripts/deploy.py {site_name} --namespace docs
```

## Structure

```
{site_name}/
├── docs/           # Documentation files
├── blog/           # Blog posts
├── src/
│   ├── css/        # Custom CSS
│   └── pages/      # Custom pages
├── static/
│   └── img/        # Static images
├── docusaurus.config.js
└── sidebars.js
```

## Adding Documentation

1. Create `.mdx` or `.md` file in `docs/`
2. Add frontmatter:
   ```markdown
   ---
   sidebar_position: 1
   title: My Doc
   ---
   ```
3. Write content in Markdown

## Configuration

Edit `docusaurus.config.js` to customize:
- Site title and tagline
- Navigation items
- Theme settings
- Plugins

## Deployment

See `scripts/` for deployment automation.
'''


def init_docusaurus(site_name: str, title: str) -> bool:
    """Initialize Docusaurus site structure."""
    base_dir = Path(site_name)
    
    # Create directories
    dirs = [
        base_dir / "docs",
        base_dir / "blog",
        base_dir / "src" / "css",
        base_dir / "src" / "pages",
        base_dir / "static" / "img",
        base_dir / "k8s",
    ]
    
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    
    # Create files
    files = {
        base_dir / "docusaurus.config.js": create_docusaurus_config(site_name, title),
        base_dir / "sidebars.js": create_sidebars(),
        base_dir / "docs" / "intro.md": create_intro_doc(site_name),
        base_dir / "blog" / f"{datetime.now().strftime('%Y-%m-%d')}-welcome.md": create_blog_post(),
        base_dir / "src" / "css" / "custom.css": create_custom_css(),
        base_dir / "Dockerfile": create_dockerfile(),
        base_dir / "nginx.conf": create_nginx_conf(),
        base_dir / "k8s" / "deployment.yaml": create_k8s_deployment(site_name),
        base_dir / "package.json": create_package_json(site_name),
        base_dir / "README.md": create_readme(site_name, title),
    }
    
    for path, content in files.items():
        with open(path, 'w') as f:
            f.write(content)
        print(f"  ✓ Created {path}")
    
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Initialize Docusaurus documentation site"
    )
    parser.add_argument("name", help="Site name (e.g., learnflow-docs)")
    parser.add_argument("-t", "--title", required=True, help="Site title")
    
    args = parser.parse_args()
    
    print(f"Initializing Docusaurus site: {args.name}")
    print("=" * 50)
    
    if init_docusaurus(args.name, args.title):
        print("\n" + "=" * 50)
        print(f"✓ Docusaurus site initialized!")
        print(f"\nNext steps:")
        print(f"  cd {args.name}")
        print(f"  npm install")
        print(f"  npm start")
        print(f"\nDeploy:")
        print(f"  python scripts/build.py {args.name}")
        print(f"  python scripts/deploy.py {args.name} --namespace docs")
        sys.exit(0)
    else:
        print("\n✗ Failed to initialize site")
        sys.exit(1)


if __name__ == "__main__":
    main()
